#!/bin/bash
#this script rchooses one of two images and
#sets is as the background depending on the day
#place this script in /etc/profile.d/ and run
#sudo chmod +x autostart 
#the path parameter can be changed to change the image displayed

currDate=`date +%j`
currDate=${currDate#0}
if (( $currDate % 2 == 0 ))
then
    feh --bg-scale ~/Pictures/afi2.jpg
else
    feh --bg-scale ~/Pictures/ts.jpg
fi
echo "did" > /home/sc/tst
